'use client';

import { useEffect, useRef, useState } from 'react';
import { getSupabase } from '@/lib/supabase';

type GameId='ten'|'f1'|'tap'|'memory';
type Mode='solo'|'duo'|'event';
const GAMES:[GameId,string,string][]=[['ten','10.000','Arrête le chrono au plus près de 10.000 s'],['f1','F1 START','Attends l’extinction des 5 feux puis frappe'],['tap','TAP 30','Fais le plus de KLIIK possible en 30 s'],['memory','MÉMOIRE','Mémorise 10 couleurs et replace-les']];
const MC=['#1d16f5','#fff500','#ff1694','#fff'];

function share(text:string,url?:string){const target=url||location.href;if(navigator.share)navigator.share({title:'KLIIK',text,url:target}).catch(()=>{});else navigator.clipboard.writeText(`${text}\n${target}`).then(()=>alert('Lien copié !'));}
function AnimatedNumber({to,decimals=0,duration=2200}:{to:number;decimals?:number;duration?:number}){const[v,setV]=useState(0);useEffect(()=>{let raf=0;const s=performance.now();const f=(n:number)=>{const p=Math.min(1,(n-s)/duration);setV(to*(1-Math.pow(1-p,3)));if(p<1)raf=requestAnimationFrame(f);};raf=requestAnimationFrame(f);return()=>cancelAnimationFrame(raf)},[to,duration]);return <>{v.toFixed(decimals)}</>}

export default function Home(){
 const[mode,setMode]=useState<Mode>('solo'),[game,setGame]=useState<GameId|null>(null),[setup,setSetup]=useState(false),[selected,setSelected]=useState<GameId[]>(['ten','f1','tap','memory']),[room,setRoom]=useState<string|null>(null),[roomId,setRoomId]=useState<string|null>(null),[players,setPlayers]=useState<string[]>([]),[nick,setNick]=useState(''),[hostNick,setHostNick]=useState(''),[host,setHost]=useState(false),[busy,setBusy]=useState(false),[started,setStarted]=useState(false),[enabled,setEnabled]=useState<Record<GameId,boolean>>({ten:true,f1:true,tap:true,memory:true});
 useEffect(()=>{const raw=localStorage.getItem('kliik-enabled-games');if(raw)try{setEnabled(JSON.parse(raw))}catch{};const p=new URLSearchParams(location.search),g=p.get('game') as GameId|null,r=p.get('room');if(g)setGame(g);if(r){setRoom(r);setMode((p.get('mode') as Mode)||'event');setHost(p.get('host')==='1');}},[]);
 useEffect(()=>{if(!room)return;const sb=getSupabase();if(!sb)return;let rid='';const refresh=async()=>{const{data:r}=await sb.from('rooms').select('id,games,status,current_game').eq('code',room).single();if(!r)return;rid=r.id;setRoomId(r.id);if(Array.isArray(r.games))setSelected(r.games);setStarted(r.status==='playing');const{data:p}=await sb.from('players').select('nickname').eq('room_id',r.id);setPlayers((p||[]).map((x:any)=>x.nickname));};refresh();const ch=sb.channel(`kliik-${room}`).on('postgres_changes',{event:'*',schema:'public',table:'players'},refresh).on('postgres_changes',{event:'UPDATE',schema:'public',table:'rooms'},refresh).subscribe();return()=>{sb.removeChannel(ch)}},[room]);
 async function createRoom(){if(!hostNick.trim()){alert('Choisis ton prénom / pseudo avant de créer la partie.');return}setBusy(true);const code=Math.random().toString(36).slice(2,8).toUpperCase(),sb=getSupabase();if(!sb){setBusy(false);alert('Connexion Supabase indisponible.');return}const{data,error}=await sb.from('rooms').insert({code,mode,games:selected,status:'lobby',current_game:0}).select('id').single();if(error||!data){setBusy(false);alert('Impossible de créer la room.');return}await sb.from('players').insert({room_id:data.id,nickname:hostNick.trim(),is_host:true});setRoomId(data.id);setRoom(code);setHost(true);setPlayers([hostNick.trim()]);setSetup(false);setBusy(false);history.replaceState({},'',`/?room=${code}&mode=${mode}&host=1`);}
 async function joinRoom(){if(!room||!nick.trim())return;const sb=getSupabase();if(!sb)return;const{data:r}=await sb.from('rooms').select('id').eq('code',room).single();if(r){await sb.from('players').insert({room_id:r.id,nickname:nick.trim(),is_host:false});setRoomId(r.id)}setNick('');}
 async function launch(){if(!roomId)return;const sb=getSupabase();if(!sb)return;const{error}=await sb.from('rooms').update({status:'playing',current_game:0}).eq('id',roomId);if(error)alert('Impossible de lancer la partie.');else setStarted(true);}
 if(game)return <GameScreen id={game} onBack={()=>{setGame(null);history.replaceState({},'','/')}}/>;
 if(room)return <Lobby room={room} mode={mode} host={host} players={players} nick={nick} setNick={setNick} join={joinRoom} selected={selected} launch={launch} started={started} onBack={()=>{setRoom(null);history.replaceState({},'','/')}}/>;
 if(setup)return <Setup mode={mode} selected={selected} setSelected={setSelected} create={createRoom} busy={busy} hostNick={hostNick} setHostNick={setHostNick} onBack={()=>setSetup(false)}/>;
 return <main className="appShell"><header className="homeHeader"><div className="logo">KL<span>II</span>K</div></header><section className="homeHero"><h1>MINI JEUX.<br/>MAXI DÉFIS.</h1><p>Choisis ton mode, joue tout de suite, défie tes potes.</p></section><nav className="modeTabs">{(['solo','duo','event'] as Mode[]).map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m==='solo'?'SOLO':m==='duo'?'DUO':'MULTI'}</button>)}</nav><section className="gameGrid">{GAMES.filter(g=>enabled[g[0]]).map(([id,title,sub])=><button key={id} className={`liveCard card-${id}`} onClick={()=>mode==='solo'?setGame(id):(setSetup(true))}><CardVisual id={id}/><div className="cardCopy"><strong>{title}</strong><span>{sub}</span></div></button>)}</section>{mode!=='solo'&&<button className="createRoomBtn" onClick={()=>setSetup(true)}>{mode==='duo'?'CRÉER UN DUEL':'CRÉER UNE ROOM'}</button>}<ScoreTicker/></main>;
}

function CardVisual({id}:{id:GameId}){const[tap,setTap]=useState(0);useEffect(()=>{if(id!=='tap')return;let n=0;const i=setInterval(()=>{n=Math.min(223,n+Math.ceil(Math.random()*9));setTap(n);if(n>=223)clearInterval(i)},70);return()=>clearInterval(i)},[id]);if(id==='ten')return <div className="cardVisual"><div className="miniTimer"><AnimatedNumber to={9.987} decimals={3}/></div></div>;if(id==='f1')return <div className="cardVisual"><div className="miniLights">{[1,2,3,4,5].map(i=><i key={i}/>)}</div></div>;if(id==='tap')return <div className="cardVisual"><div className="tapPulse"><b>KLIIK!</b></div><div style={{fontSize:'2rem',fontWeight:950,marginTop:8}}>{tap}</div></div>;return <div className="cardVisual"><div style={{position:'relative',width:'88%',margin:'0 auto',overflow:'hidden',padding:'18px 3px'}}><div className="memoDots">{[0,1,2,3,0,2,1,3,2,0].map((c,i)=><i key={i} style={{background:MC[c]}}/>)}</div><div className="memoryCardLid">KLIIK →</div></div></div>}

function Setup({mode,selected,setSelected,create,busy,hostNick,setHostNick,onBack}:{mode:Mode;selected:GameId[];setSelected:(v:GameId[])=>void;create:()=>void;busy:boolean;hostNick:string;setHostNick:(v:string)=>void;onBack:()=>void}){return <main className="fullPanel"><button className="backBtn" onClick={onBack}>← Retour</button><h1>{mode==='duo'?'DUEL':'MULTIJOUEURS'}</h1><p>Choisis les jeux. <b>Jaune = sélectionné</b>, bleu = non sélectionné.</p><div className="setupGames">{GAMES.map(([id,title])=><button key={id} className={selected.includes(id)?'sel':''} onClick={()=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id])}>{selected.includes(id)?'✓ ':''}{title}</button>)}</div><input className="nickInput" value={hostNick} onChange={e=>setHostNick(e.target.value)} placeholder="Ton prénom / pseudo (organisateur)"/><button className="bigAction" disabled={!selected.length||busy||!hostNick.trim()} onClick={create}>{busy?'CRÉATION…':mode==='duo'?'CRÉER LE DUEL':'CRÉER LA ROOM'}</button></main>}

function Lobby({room,mode,host,players,nick,setNick,join,selected,launch,started,onBack}:{room:string;mode:Mode;host:boolean;players:string[];nick:string;setNick:(s:string)=>void;join:()=>void;selected:GameId[];launch:()=>void;started:boolean;onBack:()=>void}){const url=typeof window==='undefined'?'':`${location.origin}/?room=${room}&mode=${mode}`;const qr=`https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(url)}`;const invite=`Je te défie sur ${selected.length} mini-jeu${selected.length>1?'x':''} KLIIK via le lien suivant :`;
 return <main className="fullPanel lobby"><button className="backBtn" onClick={onBack}>← Accueil</button><div className="roomCode">ROOM <b>{room}</b></div><h1>{mode==='duo'?'DUEL':'MULTI'}</h1><p>{selected.length} jeu(x) sélectionné(s)</p>{started&&<div className="resultPill">PARTIE LANCÉE ✓</div>}{host?<><div className="players"><strong>{players.length} joueur(s)</strong>{players.map((p,i)=><span key={i}>{p}{i===0?' · organisateur':''}</span>)}</div><button className="bigAction" onClick={()=>share(invite,url)}>INVITER PAR LIEN</button><details className="qrBox"><summary>📱 AFFICHER LE QR CODE</summary><img src={qr} alt="QR code pour rejoindre la partie KLIIK"/><small>Les amis présents scannent ce QR pour rejoindre directement la room.</small></details><button className="secondaryAction" disabled={players.length<2||started} onClick={launch}>{started?'PARTIE LANCÉE':'LANCER LA PARTIE'}</button></>:<><input className="nickInput" value={nick} onChange={e=>setNick(e.target.value)} placeholder="Ton prénom / pseudo"/><button className="bigAction" onClick={join} disabled={!nick.trim()}>REJOINDRE</button><div className="players">{players.map((p,i)=><span key={i}>{p}</span>)}</div>{started&&<div className="resultPill">L’organisateur a lancé la partie !</div>}</>}</main>}

function ScoreTicker(){return <div className="ticker"><div className="tickerTrack"><span>🏆 10.000 — Léa 10.001</span><span>🏁 F1 — Tom 184 ms</span><span>⚡ TAP 30 — Noa 247</span><span>🧠 MÉMOIRE — Emma 10/10</span></div></div>}
function GameScreen({id,onBack}:{id:GameId;onBack:()=>void}){return <main className={`gamePage game-${id}`}><button className="backBtn gameBack" onClick={onBack}>← Jeux</button>{id==='ten'?<Ten/>:id==='f1'?<F1/>:id==='tap'?<Tap/>:<Memory/>}</main>}
function EndActions({onReplay,onShare}:{onReplay:()=>void;onShare:()=>void}){return <div className="endActions"><button onClick={onShare}>DÉFIER UN AMI</button><button onClick={onReplay}>REJOUER</button></div>}
function Ten(){const[r,setR]=useState(false),[ms,setMs]=useState(0),[done,setDone]=useState(false);const st=useRef(0),raf=useRef(0);useEffect(()=>{if(!r)return;const f=()=>{setMs(performance.now()-st.current);raf.current=requestAnimationFrame(f)};raf.current=requestAnimationFrame(f);return()=>cancelAnimationFrame(raf.current)},[r]);const start=()=>{setDone(false);setMs(0);st.current=performance.now();setR(true)},stop=()=>{setMs(performance.now()-st.current);setR(false);setDone(true)};return <section className="gameCore"><h1>10.000</h1><p>Arrête le chrono au plus près de 10.000 secondes.</p><div className="scoreDisplay">{(ms/1000).toFixed(3)}</div>{!done&&<button className="mainPlay" onClick={r?stop:start}>{r?'STOP':'START'}</button>}{done&&<><div className="resultPill">Écart : {(Math.abs(ms-10000)/1000).toFixed(3)} s</div><EndActions onReplay={start} onShare={()=>share(`J’ai fait ${(ms/1000).toFixed(3)} s sur KLIIK. Tu peux me battre ?`,`${location.origin}/?game=ten`)}/></>}</section>}
function F1(){const[p,setP]=useState<'idle'|'lights'|'go'|'done'|'false'>('idle'),[n,setN]=useState(0),[reaction,setReaction]=useState(0);const go=useRef(0),timers=useRef<number[]>([]);const clear=()=>timers.current.forEach(clearTimeout),start=()=>{clear();setP('lights');setN(0);for(let i=1;i<=5;i++)timers.current.push(window.setTimeout(()=>setN(i),i*950));timers.current.push(window.setTimeout(()=>{setN(0);setP('go');go.current=performance.now()},5650+Math.random()*1800))},hit=()=>{if(p==='lights'){clear();setP('false')}else if(p==='go'){setReaction(performance.now()-go.current);setP('done')}};return <section className="gameCore f1Core" onPointerDown={(p==='lights'||p==='go')?hit:undefined}><h1>F1 START</h1><p>Les 5 feux rouges s’allument un par un. Appuie dès qu’ils s’éteignent tous.</p><div className="f1Lights">{[1,2,3,4,5].map(i=><i key={i} className={n>=i?'on':''}/>)}</div>{p==='idle'&&<button className="mainPlay" onPointerDown={e=>e.stopPropagation()} onClick={start}>LANCER</button>}{p==='lights'&&<b className="statusTxt">ATTENDS…</b>}{p==='go'&&<b className="statusTxt good">MAINTENANT !</b>}{(p==='done'||p==='false')&&<>{p==='done'?<div className="bigResult">{reaction.toFixed(0)} ms</div>:<div className="bigResult bad">FAUX DÉPART</div>}<EndActions onReplay={start} onShare={()=>share(`Je te défie au F1 Start KLIIK.`,`${location.origin}/?game=f1`)}/></>}</section>}
function Tap(){const[count,setCount]=useState(0),[time,setTime]=useState(30),[phase,setPhase]=useState<'idle'|'run'|'done'>('idle');useEffect(()=>{if(phase!=='run')return;const i=setInterval(()=>setTime(t=>{if(t<=1){clearInterval(i);setPhase('done');return 0}return t-1}),1000);return()=>clearInterval(i)},[phase]);const start=()=>{setCount(0);setTime(30);setPhase('run')};return <section className="gameCore"><h1>TAP 30</h1><p>Fais le plus de KLIIK possible en 30 secondes.</p>{phase==='idle'&&<button className="mainPlay" onClick={start}>START</button>}{phase==='run'&&<><div className="tapHud2">{time}s · {count} KLIIK</div><button className="tapBig" onPointerDown={()=>setCount(c=>c+1)}>KLIIK!</button></>}{phase==='done'&&<><div className="bigResult">{count} KLIIK</div><EndActions onReplay={start} onShare={()=>share(`J’ai fait ${count} KLIIK en 30 secondes. Tu peux me battre ?`,`${location.origin}/?game=tap`)}/></>}</section>}
function Memory(){const[seq,setSeq]=useState<number[]>([]),[ans,setAns]=useState<(number|null)[]>(Array(10).fill(null)),[phase,setPhase]=useState<'idle'|'memorize'|'answer'|'reveal'|'done'>('idle'),[active,setActive]=useState(0),[revealed,setRevealed]=useState(0),[msg,setMsg]=useState(''),[score,setScore]=useState(0),[lost,setLost]=useState(false);const timers=useRef<number[]>([]);const start=()=>{timers.current.forEach(clearTimeout);setSeq(Array.from({length:10},()=>Math.floor(Math.random()*4)));setAns(Array(10).fill(null));setActive(0);setRevealed(0);setScore(0);setLost(false);setMsg('Mémorise de gauche à droite →');setPhase('memorize');setTimeout(()=>{setPhase('answer');setMsg('Choisis simplement une couleur : la bille suivante est sélectionnée automatiquement.')},5000)};const choose=(c:number)=>{if(phase!=='answer')return;const a=[...ans];a[active]=c;setAns(a);const next=a.findIndex((v,i)=>i>active&&v===null);if(next>=0)setActive(next);else{const first=a.findIndex(v=>v===null);if(first>=0)setActive(first)}};const validate=()=>{if(ans.some(v=>v===null))return;setPhase('reveal');let pts=0,bad=false;seq.forEach((c,i)=>timers.current.push(window.setTimeout(()=>{const ok=ans[i]===c;if(ok)pts++;else bad=true;setScore(pts);setLost(bad);setRevealed(i+1);setMsg(ok?`✓ BILLE ${i+1} : BONNE`:`✕ BILLE ${i+1} : MAUVAISE — partie perdue`);if(i===9)setPhase('done')},(i+1)*1200)))};return <section className="gameCore memoryCore"><h1>MÉMOIRE</h1><p>Mémorise les 10 couleurs de gauche à droite → puis reproduis-les.</p>{phase==='idle'&&<button className="mainPlay" onClick={start}>START</button>}{phase!=='idle'&&<><b className={`memoryMsg ${msg.startsWith('✕')?'badMsg':msg.startsWith('✓')?'goodMsg':''}`}>{msg}</b><div className="memRows"><div className="memRow topMem">{seq.map((c,i)=><button key={i} style={{background:MC[c]}} className={(phase==='memorize'||i<revealed)?'ball':'ball covered'}><span className="lid">{i<revealed?'':i+1}</span></button>)}</div><div className="memRow">{ans.map((c,i)=><button key={i} onClick={()=>phase==='answer'&&setActive(i)} className={`ball answerBall ${active===i&&phase==='answer'?'activeBall':''}`} style={{background:c===null?'#777':MC[c]}}>{i+1}</button>)}</div></div>{phase==='answer'&&<><div className="palette">{MC.map((c,i)=><button key={i} onClick={()=>choose(i)} style={{background:c}} aria-label={`Couleur ${i+1}`}/>)}</div><button className="mainPlay" disabled={ans.some(v=>v===null)} onClick={validate}>VALIDER</button></>}{(phase==='reveal'||phase==='done')&&<div className="resultPill">{lost?'PARTIE PERDUE':'PARFAIT'} · {score}/10 bonnes</div>}{phase==='done'&&<EndActions onReplay={start} onShare={()=>share(`J’ai fait ${score}/10 au jeu Mémoire KLIIK. À toi !`,`${location.origin}/?game=memory`)}/>}</>}</section>}
